name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install Tarpaulin for Coverage
        run: cargo install cargo-tarpaulin
      - name: Run Tests with Coverage
        run: |
          cargo tarpaulin --out Xml
        env:
          RUSTFLAGS: '-C link-dead-code'
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./cobertura.xml  # Use the generated XML coverage report
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}